### PR TITLE
Feature/slack campaign size

### PR DESCRIPTION
**Pull request by caldwellst**
Addresses #160. Waiting to merge #182 first.

### CODE REVIEW

**Comment by caldwellst** [comment]
@hannahker How were you testing in the `#hdx-signals-bot-testing` channel on Slack? Don't see any parameters we can pass to the GitHub runs?

**Comment by hannahker** [comment]
@caldwellst I've just been running the script locally to test!

**Comment by caldwellst** [comment]
Okay, finally was able to have a signal that I could test with, didn't want to generate a test dataset simply for that purpose. Will eventually need to figure out how to better set this up for testing, but good for review now! See the latest bot post in `#hdx-signals-bot-testing`  for how it looks.

**Review by hannahker — APPROVED** [review]
LGTM!

**Pull request merged**
