### PR TITLE
Suppress warnings in map_food_insecurity

### PR DESCRIPTION
**Pull request by caldwellst**

### CODE REVIEW

**Review by hannahker — APPROVED** [review]
LGTM!

**Comment by zackarno** [comment]
the suppressWarnings on `fun.geometery` works!  Also another solution was found in #83 I believe

**Comment by zackarno** [comment]
the suppressWarnings on `fun.geometery` works!  Also another solution was found in #83 I believe

**Comment by caldwellst** [comment]
#83 didn't resolve the issue. It resolved the issue in the linked SO post because calculating the centroid explicitly removed a specific warning, but the specific warning of plotting coordinates was still there because `st_centroid()` still returned coordinates. So now for all of those point plotting I am using `suppressWarnings()` around the `fun.geometry`.

**Pull request merged**
