### PR TITLE
Fix ai_summarizer calls

### LINKED ISSUE #176: Pass `location` to `ai_summarizer_without_location`
With the merge of #166, we're getting some errors in workflow runs because this function is missing the `location` parameter. Eg - see [this](https://github.com/OCHA-DAP/hdx-signals/actions/runs/9568130285) run

### PR DESCRIPTION
**Pull request by caldwellst**
Fixes #176. Testing in [these](https://github.com/OCHA-DAP/hdx-signals/actions/runs/9571472364) [three](https://github.com/OCHA-DAP/hdx-signals/actions/runs/9571468278) [actions](https://github.com/OCHA-DAP/hdx-signals/actions/runs/9571461350).

### CODE REVIEW

**Comment by caldwellst** [comment]
Had to merge #175 to main and then to this branch to fully test!

**Comment by caldwellst** [comment]
Now testing for [ACLED](https://github.com/OCHA-DAP/hdx-signals/actions/runs/9571541294), [JRC](https://github.com/OCHA-DAP/hdx-signals/actions/runs/9571544001), and [IDMC](https://github.com/OCHA-DAP/hdx-signals/actions/runs/9571547388).

**Comment by caldwellst** [comment]
Re-running all 3. [ACLED](https://github.com/OCHA-DAP/hdx-signals/actions/runs/9571681216), [JRC](https://github.com/OCHA-DAP/hdx-signals/actions/runs/9571682973), [IDMC](https://github.com/OCHA-DAP/hdx-signals/actions/runs/9571685435).

**Comment by caldwellst** [comment]
@hannahker Finally all 3 succeeded!

**Review by hannahker — APPROVED** [review]
Excellent! This is good motivation to get that testing work done!

**Pull request merged**
